# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    # Install Python 3.x
    - name: Set up Python 3.x
    - uses: actions/setup-python@v2
    with:
      python-version: 3.x
      architecture: 'x64'
    #Install dependencies   
    - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools
    
    # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |  
          echo what is in this directory?
          ls -a
          echo
          echo is Python installed?
          python --verion
          echo
          is git installed?
          git --version
          echo

